version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
            yarn --version
      - run:
          name: yarn-install-deps
          command: yarn install
      - run:
          name: test
          command: yarn test